package casino;

public enum Habilidades {	
    ROBO,
    BLOQUEO,
    DESCUENTO,
    MULTIPLICADOR,
    REVELACION
}
//EXPLICACION UNA CLASE ENUM REPRESENTA UN GRUPO DE CONSTANTES
//COMO UNA CLASE ESTAS TIENEN SUS ATRIBUTOS Y METODOS, SU UNICA DIFERENCIA ES QUE SON FINAL (ES DECIR QUE NO SOBREESCRITAS)